services:
  db:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: services_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uapp -papp -h 127.0.0.1 --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  api-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../.env.docker
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      TZ: "America/Argentina/Buenos_Aires"
    # Montás el código del host pero preservás node_modules en un volumen
    volumes:
      - ../:/app
      - api_dev_node_modules:/app/node_modules

volumes:
  db_data:
  api_dev_node_modules:
