services:
  db:
    image: mysql:8.0
    container_name: docker-dev-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    container_name: docker-dev-adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  api:
    image: node:20-alpine
    container_name: docker-dev-api
    working_dir: /app
    volumes:
      - ..:/app
    env_file:
      - .env.dev        
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -lc "npm ci && npm run start:dev"

volumes:
  db_data_dev:
