version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: services
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      # DB (ajustá según tu TypeORM config)
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: app
      DB_PASS: app
      DB_NAME: services
      # JWT
      JWT_SECRET: "change-me"
      JWT_REFRESH_SECRET: "change-me-too"
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
