FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development

# deps para desarrollo
COPY package*.json ./
RUN npm ci

# (en build se copia todo, pero en runtime vas a montar el host)
COPY . .

EXPOSE 3000
CMD ["npm","run","start:dev"]

