name: CI e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ayuda a Codecov a comparar contra el base

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # opcional:
      # - run: npm run lint
      # - run: npm run build

      - name: Run e2e (con cobertura)
        env:
          CI: true
        run: npm run test:e2e

      - name: Subir coverage como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          # Si el repo es público, el token no es necesario.
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: e2e
          # No rompas el job si Codecov falla o la meta no se cumple
          fail_ci_if_error: false
          verbose: true
