coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: auto         # objetivo dinámico basado en la rama base
        threshold: 2%        # tolera una caída pequeña
        informational: true  # no bloquea el check (evita el ❌)
    patch:
      default:
        target: auto
        threshold: 2%
        informational: true

comment:
  layout: "reach, diff, files"
  require_changes: false
  behavior: default
